name: inception


services:
  nginx:
    env_file: ".env"
    container_name: nginx
    build: 
      context:
        requirements/nginx/.
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        CERT: ${CERT}
        CERT_KEY: ${CERT_KEY}
        CERT_REQUEST: ${CERT_REQUEST}
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - docker-network
    restart: always
    depends_on:
      - wordpress-php

  wordpress-php:
    env_file: .env
    container_name: wordpress-php
    build:
      context: requirements/wordpress/.
      args:
        MYSQL_VOL: ${MYSQL_VOL}
        MYSQL_ROOT: ${MYSQL_ROOT}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
        DB_NAME: ${DB_NAME}
        WP_URL: ${WP_URL} 
        WP_TITLE: ${WP_TITLE}
        WP_ADMIN: ${WP_ADMIN}
        WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
        WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
        WP_USER: ${WP_USER}
        WP_USER_EMAIL: ${WP_USER_EMAIL}
        WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html/
    depends_on:
      - mariadb
    networks:
      - docker-network
    restart: always

  mariadb:
    container_name: mariadb
    build: 
      context: requirements/mariadb/
      args:
        DB_NAME: ${DB_NAME}
        MYSQL_ROOT: ${MYSQL_ROOT}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_VOL: ${MYSQL_VOL}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
      dockerfile: Dockerfile 
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - docker-network

networks:
  docker-network:
    name: docker-network
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /home/federico/Desktop/Inception/src/data/wordpress/
  db:
    driver_opts:
      type: none
      o: bind
      device: /home/federico/Desktop/Inception/src/data/DB/


  # mariadb:
    # build: requirements/mariadb/.
    # container_name: mariadb
    # volumes:
      # - $(MYSQL_VOL):/var/lib/mysql'
